### ISSUE TITLE
memory cpu usage

### ISSUE THREAD

**Issue by dwaggott** [philres/nextgenmap-lr#1]
Hey! Just trying this on a 10x human genome. Originally, I tried chunks of 50k reads on 4GB of RAM and 1 thread but got lot's of memory failures. Do you have a sense of how the memory scales? Would you recommend 10GB RAM regardless of threads and input size? Is there a sweetspot? It's easier for me to run lot's of small jobs.

Thanks!

**Comment by philres** [comment]
Hi,

for ngmlr RAM usage depends mostly on what genome you are mapping to and on the number of threads you are using. Number of reads does not have any impact on RAM usage.

For a human genome you will need at least 6 GB of RAM (8 GB if you want to be on the safe side) when mapping with one thread.

What we usually do for larger human data sets is splitting the input data into 2 GB FASTQ (around 300k reads) files and map all 2GB files independently with ngmlr using 10 threads. Mapping to the human genome with 10 threads will require around 12 GB of RAM (15 GB if you want to be on the safe side). This reduces overall RAM usage quite a lot compared to running 6-8 GB jobs with one thread.

Hope that helped. Let me know if you have any other questions.

Philipp
